import Navbar from '../../components/layout/Navbar';
import Footer from '../../components/layout/Footer';

export default function TermsPage() {
  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg-base)', display: 'flex', flexDirection: 'column' }}>
      <Navbar />

      <div style={{ background: '#000', color: '#fff', padding: '4rem 1.5rem' }}>
        <div style={{ maxWidth: 800, margin: '0 auto' }}>
          <h1 style={{ fontFamily: 'var(--font-display)', fontSize: '3rem', marginBottom: '1rem' }}>Terms of Service</h1>
          <p style={{ fontSize: '1.1rem', opacity: 0.8 }}>The legal architecture of the DebateHub ecosystem.</p>
        </div>
      </div>

      <div style={{ maxWidth: 800, margin: '3rem auto', padding: '0 1.5rem', color: 'var(--text-secondary)', lineHeight: 1.8, flex: 1, width: '100%' }}>
        <p style={{ fontSize: '1.1rem', marginBottom: '3rem' }}>Welcome to DebateHub. By accessing our platform, you implicitly agree to abide by these Terms of Service.</p>

        <section style={{ marginBottom: '3rem' }}>
          <h3 style={{ fontSize: '1.35rem', color: 'var(--text-primary)', marginBottom: '1rem', borderBottom: '1px solid var(--border)', paddingBottom: '0.5rem' }}>Content Ownership</h3>
          <p>Users retain all intellectual property rights to the original arguments and debates they forge on DebateHub. However, by posting content here, you grant DebateHub a worldwide, irrevocable right to display, modify, summarize, and distribute these arguments globally within the application network.</p>
        </section>

        <section style={{ marginBottom: '3rem' }}>
          <h3 style={{ fontSize: '1.35rem', color: 'var(--text-primary)', marginBottom: '1rem', borderBottom: '1px solid var(--border)', paddingBottom: '0.5rem' }}>Moderation & Liability</h3>
          <p>DebateHub admins, alongside our integrated AI toxicity engines, reserve the right to ban accounts and remove arguments that breach our Community Guidelines at any time, with or without prior warning. We are not liable for the opinions or content generated by users on this platform.</p>
        </section>

        <section>
          <h3 style={{ fontSize: '1.35rem', color: 'var(--text-primary)', marginBottom: '1rem', borderBottom: '1px solid var(--border)', paddingBottom: '0.5rem' }}>Mock Economics Clause</h3>
          <p>Any funds referenced, subscription tiers selected, or numerical reputation units scored are completely simulated for UI demonstration purposes. Subscriptions hold no actual legal bounds, nor real-world financial cost, in this demonstration environment.</p>
        </section>
      </div>
      <Footer />
    </div>
  );
}
